software: nodejs
name: 应用运行环境-NodeJs
baseImage: aliyun_3_9_x64_20G_alibase_20231219.vhd # 使用有效的公共模板作为占位符
imageInitScript: |-
  #!/bin/bash
  yum -y install git
  cat>install_nvm.sh<<EOF
  #!/bin/bash
  # 注意build环境需要公网
  git clone https://gitee.com/mirrors/nvm.git ~/.nvm || (echo "git clone failed" && exit 1)
  cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
  echo ". ~/.nvm/nvm.sh" >> ~/.bashrc
  echo "export NVM_NODEJS_ORG_MIRROR=https://npmmirror.com/mirrors/node" >> ~/.bashrc
  source ~/.bashrc
  nvm install v20.12.2
  EOF
  bash install_nvm.sh

  cat>~/node_example.js<<EOF
  const http = require('http');
  const hostname = '0.0.0.0';
  const port = 80;
  const server = http.createServer((req, res) => { 
      res.statusCode = 200;
      res.setHeader('Content-Type', 'text/plain');
      res.end('Hello World\n');
  }); 

  server.listen(port, hostname, () => { 
      console.log(`Server running at http://${hostname}:${port}/`);
  });
  EOF
  #nohup node ~/node_example.js &

  cat>~/README<<EOF
  此应用模板在root用户下部署了nvm和node.js v20.12.2版本
  如果您想在其他用户下部署nvm和node.js，将install_nvm.sh复制到该用户目录下，使用该用户身份执行
  查看已安装版本：
    nvm ls
  您可以使用nvm安装其他node.js版本：
    nvm install 版本号
  切换node版本号：
    nvm use 版本号

  使用下面的命令测试node.js:
  nohup node /root/node_example.js &
  访问http://<IP地址>，应该返回Hello World
  EOF